/// Rust code generator for modern type-safe IPC

use super::{CodeGenerator, CodegenError};
use crate::parser::ast::*;

pub struct RustCodeGenerator {
    _module_name: String,
}

impl RustCodeGenerator {
    pub fn new() -> Self {
        Self {
            _module_name: "mach_ipc".to_string(),
        }
    }
}

impl Default for RustCodeGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl CodeGenerator for RustCodeGenerator {
    fn generate_user_header(&self, subsystem: &Subsystem) -> Result<String, CodegenError> {
        let mut output = String::new();

        output.push_str("//! Client stubs for ");
        output.push_str(&subsystem.name);
        output.push_str("\n//! Auto-generated by mig-rust\n\n");

        output.push_str("use mach::kern_return::*;\n");
        output.push_str("use mach::port::*;\n");
        output.push_str("use mach::message::*;\n\n");

        // TODO: Generate Rust trait and implementation

        Ok(output)
    }

    fn generate_user_impl(&self, _subsystem: &Subsystem) -> Result<String, CodegenError> {
        // In Rust, implementation is in the same file as the trait
        Ok(String::new())
    }

    fn generate_server_header(&self, subsystem: &Subsystem) -> Result<String, CodegenError> {
        let mut output = String::new();

        output.push_str("//! Server stubs for ");
        output.push_str(&subsystem.name);
        output.push_str("\n//! Auto-generated by mig-rust\n\n");

        output.push_str("use mach::kern_return::*;\n");
        output.push_str("use mach::port::*;\n");
        output.push_str("use mach::message::*;\n\n");

        // TODO: Generate server trait and dispatcher

        Ok(output)
    }

    fn generate_server_impl(&self, _subsystem: &Subsystem) -> Result<String, CodegenError> {
        Ok(String::new())
    }
}
